#! /bin/sh
# /etc/init.d/gridlocal
#

# to install Gridlan service
# cp gridlocal /etc/init.d/
# chmod 755 /etc/init.d/gridlocal
# update-rc.d gridlocal defaults

### BEGIN INIT INFO
# Provides:          gridlocal
# Required-Start:    libvirt-bin
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Gridlan service
# Description:       Enable service provided by daemon.
### END INIT INFO

# Some things that run always
touch /var/lock/gridlocal

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Creating tap6 interface"
    openvpn --mktun --dev tap6
    ifconfig tap6 up
    sleep 1
    echo "Connecting to the Gridlan server. Log file: /opt/gridlocal/vpn.log"
    openvpn --config /opt/gridlocal/vpn-cliente-grid.conf --tls-client > /opt/gridlocal/vpn.log &
    sleep 8
    echo "Starting up vm from /opt/gridlocal/gridnode.xml."
    virsh create /opt/gridlocal/gridnode.xml 
    ;;
  stop)
    echo "Turning off VM."
    virsh destroy $(cat /opt/gridlocal/host)
    echo "Closing VPN connection."
    kill $(ps aux|grep vpn-cliente-gri[d]|awk '{print $2}')
    echo "Turning off tap6 interface."
    ifconfig tap6 down
    openvpn --rmtun --dev tap6
    ;;
  status)
    echo -----------
    echo "Checking tap6 interface"
    ifconfig|grep tap6
    echo -----------
    echo "VPN connection PID:" $(ps aux|grep vpn-cliente-gri[d]|awk '{print $2}')
    echo "Last lines from log:"
    tail -n 4 /opt/gridlocal/vpn.log
    echo -----------
    virsh list
    echo -----------
    ;;
  restart)
    echo "Turning off VM."
    virsh destroy $(cat /opt/gridlocal/host)
    echo "Closing VPN cpnnection."
    kill $(ps aux|grep vpn-cliente-gri[d]|awk '{print $2}')
    echo "Turning off tap6 interface."
    ifconfig tap6 down
    openvpn --rmtun --dev tap6
    sleep 2
    echo "Creating tap6 interface."
    openvpn --mktun --dev tap6
    ifconfig tap6 up
    sleep 1
    echo "Connecting to the Gridlan server. Log file: /opt/gridlocal/vpn.log"
    openvpn --config /opt/gridlocal/vpn-cliente-grid.conf --tls-client > /opt/gridlocal/vpn.log &
    sleep 8
    echo "Starting up vm from /opt/gridlocal/gridnode.xml.."
    virsh create /opt/gridlocal/gridnode.xml 
    ;;
  *)
    echo "Usage: /etc/init.d/gridlocal {start|stop|status|restart}"
    exit 1
    ;;
esac

exit 0
